### ISSUE TITLE
  error: subprocess-exited-with-error    × python setup.py egg_info did not run successfully.   │ exit code: 1   ╰─> [6 lines of output]       Traceback (most recent call last):         File "<string>", line 2, in <module>         File "<pip-setuptools-caller>", line 34, in <module>         File "C:\GroundingDINO\setup.py", line 27, in <module>           import torch       ModuleNotFoundError: No module named 'torch'       [end of output]    note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed  × Encountered error while generating package metadata. ╰─> See above for output.  note: This is an issue with the package mentioned above, not pip. hint: See above for details.

### ISSUE THREAD

**Issue by HassanBinHaroon** [HassanBinHaroon/GroundingDINO-Inference#2]
![Screenshot 2023-04-27 175034](https://user-images.githubusercontent.com/104098902/234867246-f0efa7ae-a7df-4de9-93a4-2aced44dd113.png)

**Comment by HassanBinHaroon** [comment]
try "**pip install -r requirements.txt**" this command for the installation.

**Comment by HassanBinHaroon** [comment]
Use the same fix for the following shown error.

![Screenshot 2023-04-27 175034](https://user-images.githubusercontent.com/104098902/234868251-54b05433-d986-4433-9739-9e7091120870.png)
